#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd /var/www/html
git pull
chown -Rf nginx:nginx /var/www/html

# Run build script if exists
if [ ! -z "$BUILD_SCRIPT" ]; then
    # Add execute permission if it is file
    if [ -f "$BUILD_SCRIPT" ]; then
    chmod +x $BUILD_SCRIPT
    fi
    $BUILD_SCRIPT
fi
